spring.application.name=web-ban-hoa
spring.profiles.active=prod

spring.datasource.url=jdbc:postgresql://db.lphgkwtdzkegmhrtxtwq.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=webbanhoa123@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

spring.h2.console.enabled=false

server.error.include-message=always
server.error.include-stacktrace=never

security.admin-role-header=X-Role

# JWT Configuration (Supabase)
jwt.secret=rlct0CbI5kDW1Rpt8OCjvX6a74WpT2k+hjeemdIVVsMQVjBosb/V2jzhL9nK6+PuyLuNwmT3xcol/rNu4MfjhA==
jwt.issuer=https://lphgkwtdzkegmhrtxtwq.supabase.co/auth/v1
jwt.jwks-url=https://lphgkwtdzkegmhrtxtwq.supabase.co/auth/v1/.well-known/jwks.json

r2.enabled=true
r2.account-id=7a620657d212cc8cfd22b9d9b642f657
r2.access-key=96777e49c9c5b66399fcf544f6a0107
r2.secret-key=8e14631007f8f93b9cb5dbb27d7e55d86c49df7118d7720af240c68a58757f6ea
r2.bucket=florastore
r2.region=auto
r2.public-base-url=

payments.vietqr.api-base-url=https://api.vietqr.io
payments.vietqr.client-id=f65557ed-eaaa-4892-a8f6-72828568f531
payments.vietqr.api-key=c0b3b05c-44b6-438d-83e7-76efc3ce57b9
payments.vietqr.webhook-secret=
payments.vietqr.signing-secret=

payments.sepay.api-base-url=https://my.sepay.vn/userapi
payments.sepay.api-token=OGUFZZIQAL7AYPHTLMGRVKMPROIJUP5VWMNEXKJFQCSRI8DTAU3SZCBE8CV1O1HD
payments.sepay.webhook-secret=OGUFZZIQAL7AYPHTLMGRVKMPROIJUP5VWMNEXKJFQCSRI8DTAU3SZCBE8CV1O1HD
payments.sepay.signing-secret=

payments.bank.account-expected=0327207918
payments.bank.account-number=0327207918
payments.bank.account-name=QUACH THI NGOC LINH
payments.bank.name=MB Bank
payments.bank.bin=970422

payments.qr.expiry-minutes=15
payments.polling-interval-seconds=15
payments.reminder-interval-seconds=30
payments.amount-tolerance=1000

payments.webhook.ip-whitelist=127.0.0.1,::1,::ffff:127.0.0.1
payments.webhook.timestamp-tolerance-minutes=5
payments.webhook.future-tolerance-minutes=1

