ALTER TABLE user_preferences
ADD COLUMN signature_wrap BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN eco_delivery BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN ribbon_color VARCHAR(20) NOT NULL DEFAULT 'blush';
