CREATE TABLE IF NOT EXISTS collaborator_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    badge VARCHAR(20) NOT NULL DEFAULT 'STAFF',
    position_title VARCHAR(120) NOT NULL DEFAULT 'Shop Collaborator',
    position_description VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_collaborator_profiles_badge CHECK (badge IN ('STAFF', 'ADMIN'))
);

CREATE OR REPLACE FUNCTION set_collaborator_profiles_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_collaborator_profiles_updated_at ON collaborator_profiles;

CREATE TRIGGER trg_collaborator_profiles_updated_at
BEFORE UPDATE ON collaborator_profiles
FOR EACH ROW
EXECUTE FUNCTION set_collaborator_profiles_updated_at();
