CREATE TABLE IF NOT EXISTS collaborator_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    badge VARCHAR(20) NOT NULL,
    position_title VARCHAR(120) NOT NULL,
    position_description VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_collaborator_profiles_badge CHECK (badge IN ('STAFF', 'ADMIN'))
);

CREATE INDEX IF NOT EXISTS idx_collaborator_profiles_user_id ON collaborator_profiles(user_id);
