CREATE TABLE IF NOT EXISTS collaborator_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    badge VARCHAR(20) NOT NULL DEFAULT 'STAFF',
    position_title VARCHAR(120) NOT NULL DEFAULT 'Shop Collaborator',
    position_description VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_collaborator_profiles_badge CHECK (badge IN ('STAFF', 'ADMIN'))
);

ALTER TABLE collaborator_profiles
    ADD COLUMN IF NOT EXISTS badge VARCHAR(20),
    ADD COLUMN IF NOT EXISTS position_title VARCHAR(120),
    ADD COLUMN IF NOT EXISTS position_description VARCHAR(255),
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

UPDATE collaborator_profiles
SET
    badge = COALESCE(badge, 'STAFF'),
    position_title = COALESCE(position_title, 'Shop Collaborator'),
    created_at = COALESCE(created_at, NOW()),
    updated_at = COALESCE(updated_at, NOW());

ALTER TABLE collaborator_profiles
    ALTER COLUMN badge SET NOT NULL,
    ALTER COLUMN position_title SET NOT NULL,
    ALTER COLUMN created_at SET NOT NULL,
    ALTER COLUMN updated_at SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'chk_collaborator_profiles_badge'
    ) THEN
        ALTER TABLE collaborator_profiles
            ADD CONSTRAINT chk_collaborator_profiles_badge
            CHECK (badge IN ('STAFF', 'ADMIN'));
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_collaborator_profiles_user_id
    ON collaborator_profiles(user_id);
